#=
# Inverse calibration

The [Inverse ice history](@ref) example reconstructed an unknown *ice load* from
surface observations, holding the solid Earth fixed. This example does the
complementary calibration: the ice history is **known**, and we invert for the
unknown **solid-Earth parameters** — the mantle viscosity structure and the
densities — that best reproduce observed deformation. This is the typical setup
when tuning a GIA model against a more expensive 3-D reference model or against
geophysical data.

The unknowns are wrapped in a [`Test2Encoding`](@ref) (19 parameters):

- a background `log10(viscosity)` plus **four Gaussian viscosity anomalies**, each
  with a centre `(μₓ, μᵧ)`, a width `σ` and an amplitude, and
- the upper-mantle and lithosphere **densities** `ρ_uppermantle`, `ρ_litho`.

We use a [`ParameterInversion`](@ref) (rather than the `IceLoadInversion` of the
previous example) and observe the vertical uplift over the **full field** at
several times — a rich `(x, y, t)` dataset that, as we will see, constrains even
the viscosity/density trade-off that is often degenerate with sparser data.
=#

using FastIsostasy, CairoMakie, Optim
import Enzyme                      # loading Enzyme activates the AD extension
using Random: seed!
using Printf

#=
## Fixed configuration and the known ice load

Same 32×32 grid and 10 kyr glacial cycle as before. The ice load is a single
broad Vialov dome (2000 km radius) whose thickness follows the glacial-cycle
sawtooth — broad enough that all four viscosity anomalies sit under load and are
therefore sensed by the deformation.
=#

W, n = 3.0e6, 5
domain = RegionalDomain(W, n)
knot_times = [0.0, 5.0e3, 8.0e3, 9.0e3, 1.0e4]
t_span = (0.0, 1.0e4)

## a radially-symmetric Vialov dome H(r) = Hc·max(1 − (r/L)^{4/3}, 0)^{3/8}
function vialov_dome(domain, xc, yc, L, Hc)
    r = @. sqrt((domain.X - xc)^2 + (domain.Y - yc)^2)
    return @. Hc * max(1 - (r / L)^(4 // 3), 0)^(3 // 8)
end

H_dome = vialov_dome(domain, 0.0, 0.0, 2.0e6, 2.5e3)
sawtooth = [0.0, 0.4, 1.0, 0.5, 0.0]
H_snapshots = [s .* H_dome for s in sawtooth]
fig = plot_load(domain, H_snapshots[3])   # the LGM snapshot

#=
## The unknowns and their scaling

The 19 parameters span decades of viscosity, millions of metres of anomaly
position/width, and thousands of kg/m³ of density. As in the ice-history example,
`Test2Encoding` takes a `scale` vector so the optimization variable is
dimensionless and O(1) — the physical value of parameter `i` is `θ[i]·scale[i]`.
=#

gscale = [1.0e6, 1.0e6, 1.0e6, 1.0]                 # (μₓ, μᵧ, σ, amp) per Gaussian
scales = vcat(1.0, repeat(gscale, 4), 1.0e3, 1.0e3) # + two densities
enc = Test2Encoding(scale = scales)

## ground truth in physical units → normalised
θ_phys = [21.0,
    -1.0e6, -1.0e6, 8.0e5,  0.5,      # soft anomaly, SW
     1.0e6,  1.0e6, 8.0e5, -0.5,      # stiff anomaly, NE
    -1.0e6,  1.0e6, 7.0e5,  0.3,      # soft anomaly, NW
     1.0e6, -1.0e6, 7.0e5, -0.3,      # stiff anomaly, SE
    3400.0, 3200.0]                   # ρ_uppermantle, ρ_litho
θ_true = θ_phys ./ scales

#=
## The simulation template

The ice interpolation is built from the known snapshots, so `ParameterInversion`
never touches it — `reconstruct!` for `Test2Encoding` only writes the viscosity
field and the two densities. As before we use the fixed-step [`EulerIntegrator`](@ref)
integrator and a [`SmoothTransition`](@ref) for AD.
=#

function build_sim()
    it = TimeInterpolatedIceThickness(knot_times, H_snapshots, domain)
    bcs = BoundaryConditions(domain, ice_thickness = it)
    se = SolidEarth(domain; lithosphere = LaterallyVariableLithosphere(),
        layer_boundaries = [88.0e3], layer_viscosities = [1.0e21])
    opts = SolverOptions(; show_progress = false, transition = SmoothTransition(10.0),
        integ = EulerIntegrator(dt = 500.0))
    nout = NativeOutput(t = Float64[], vars = Symbol[], T = Float64)
    return Simulation(domain, bcs, RegionalSeaLevel(), se, t_span;
        opts = opts, nout = nout)
end
sim = build_sim()

#=
## Synthetic full-field observations

We observe the vertical uplift at every interior cell, at five times through the
cycle — 676 points × 5 times = 3380 measurements constraining 19 parameters. The
data are generated by a forward run at `θ_true`.
=#

pts = [CartesianIndex(i, j) for i in 4:29 for j in 4:29]
obs_times = [2.0e3, 4.0e3, 6.0e3, 8.0e3, 1.0e4]

obs0 = Observation(VerticalUpliftObservable(), pts, obs_times,
    zeros(length(pts) * length(obs_times)); σ = 0.5)
prob_gt = ParameterInversion(sim, enc, [obs0])
reconstruct!(sim, θ_true, enc)
preds = FastIsostasy.allocate_predictions(prob_gt)
FastIsostasy.forward_predict!(preds, prob_gt)
data = copy(preds[1])

obs = Observation(VerticalUpliftObservable(), pts, obs_times, data; σ = 0.5)
prob = ParameterInversion(sim, enc, [obs])
@printf("loss(θ_true) = %.3e\n", loss(prob, θ_true))

#=
## Gradient check and inversion

We perturb the truth to an initial guess and confirm the AD gradient against
finite differences, then minimise with L-BFGS.
=#

seed!(3)
θ0 = copy(θ_true)
θ0[1]      += 0.15 * randn()         # background viscosity
θ0[2:17]  .+= 0.10 .* randn(16)      # Gaussian centres / widths / amplitudes
θ0[18:19] .+= 0.10 .* randn(2)       # densities (≈ ±100 kg/m³)

fd_dir(p, θ, e; ε = 1e-4) = (loss(p, θ .+ ε .* e) - loss(p, θ .- ε .* e)) / (2ε)
g = similar(θ0)
FastIsostasy.gradient!(g, prob, θ0)
for i in (1, 2, 18)
    e = zeros(19); e[i] = 1.0
    @printf("θ[%2d]:  AD = % .4e   FD = % .4e\n", i, g[i], fd_dir(prob, θ0, e))
end

@printf("loss(θ0) = %.3e\n", loss(prob, θ0))
result = solve!(prob, θ0; optimizer = LBFGS(), iterations = 100, store_trace = true)
θ_hat = Optim.minimizer(result)
@printf("loss(θ̂)  = %.3e\n", loss(prob, θ_hat))

fig = Figure(size = (500, 350))
ax = Axis(fig[1, 1], xlabel = "L-BFGS iteration", ylabel = "loss", yscale = log10,
    title = "Convergence")
lines!(ax, Optim.f_trace(result), color = :seagreen, linewidth = 2)
fig

#=
## Recovery

Both the viscosity structure and the densities are recovered. The physical
parameters:
=#

php = θ_hat .* scales
ptp = θ_true .* scales
@printf("log10 η background:  truth %.3f   recovered %.3f\n", ptp[1], php[1])
@printf("ρ_uppermantle:       truth %.0f     recovered %.1f  (kg/m³)\n", ptp[18], php[18])
@printf("ρ_litho:             truth %.0f     recovered %.1f  (kg/m³)\n", ptp[19], php[19])

#=
The recovered viscosity field matches the truth to a few thousandths of a decade:
=#

reconstruct!(sim, θ_true, enc)
logη_true = log10.(copy(sim.solidearth.effective_viscosity))
reconstruct!(sim, θ_hat, enc)
logη_hat = log10.(copy(sim.solidearth.effective_viscosity))
@printf("viscosity field: max|Δlog10η| = %.4f decades\n",
    maximum(abs.(logη_hat .- logη_true)))

x = domain.x ./ 1e3
fig = Figure(size = (900, 320))
for (j, (Z, ttl, cmap, crange)) in enumerate((
        (logη_true, "true log10 η", :viridis, (20.4, 21.6)),
        (logη_hat, "recovered log10 η", :viridis, (20.4, 21.6)),
        (logη_hat .- logη_true, "error (decades)", :balance, (-0.02, 0.02))))
    ax = Axis(fig[1, j], aspect = DataAspect(), title = ttl)
    hidedecorations!(ax)
    hm = heatmap!(ax, x, x, Z, colormap = cmap, colorrange = crange)
    Colorbar(fig[2, j], hm, vertical = false, width = Relative(0.8))
end
fig

#=
## A note on identifiability

Viscosity and density are often *correlated* unknowns: raising the mantle density
and stiffening the mantle can produce similar surface responses, so with sparse
data they trade off and cannot be recovered independently. Here the full-field,
multi-time observation is rich enough (3380 constraints on 19 parameters) to break
that degeneracy — the densities come back to better than 1 kg/m³. With realistic,
sparse observations one should expect wider posterior uncertainty on the densities
and may prefer to fix them, or add a prior, rather than invert them freely.
=#
